linters:
  enable:
  - dogsled
  - dupl
  - exportloopref
  - gocritic
  - gocyclo
  - gosimple
  - govet
  - ineffassign
  - misspell
  - nakedret
  - prealloc
  - revive
  - staticcheck
  - stylecheck
  - typecheck
  - unconvert
  - unused
  fast: false
  disable-all: true

linters-settings:
  gosec:
    excludes:
    - G102
    - G402
    - G505
  dogsled:
    max-blank-identifiers: 5
