version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - dogsled
    - dupl
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    gosec:
      excludes:
        - G402
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - builtin$
      - examples$
      - third_party$
      - vendor$
formatters:
  exclusions:
    generated: lax
    paths:
      - builtin$
      - examples$
      - third_party$
      - vendor$
