site_name: OneAuth

site_url: https://oneauth.vitalvas.dev
docs_dir: docs/
repo_name: 'vitalvas/oneauth'
repo_url: 'https://github.com/vitalvas/oneauth'
edit_uri: edit/master/docs/docs/

theme:
  name: 'material'
  language: en
  icon:
    logo: material/shield-home
    repo: fontawesome/brands/github
  palette:
    scheme: default
    primary: teal
    accent: blue
  features:
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - toc.follow

markdown_extensions:
  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true

extra:
  analytics:
    provider: google
    property: G-B11JFXW6PV
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vitalvas/oneauth/discussions
      name: Discussions
