site_name: OneAuth

docs_dir: docs/
repo_name: 'vitalvas/oneauth'
repo_url: 'https://github.com/vitalvas/oneauth'
edit_uri: edit/master/docs/docs/

theme:
  name: 'material'
  language: en
  icon:
    logo: material/shield-home
    repo: fontawesome/brands/github
  palette:
    primary: teal

markdown_extensions:
  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji

plugins:
  - git-revision-date-localized
