name: tests

on:
  pull_request:
    branches:
      - master
    types: [closed]
  push:
    paths:
      - '**.go'
      - '**.sh'
      - 'go.mod'
      - 'go.sum'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - 'ubuntu-20.04'
          - macos-latest
          # - macos-latest-xlarge  # TODO: enable on release (costs required)

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install deps for Linux
        if: matrix.os == 'ubuntu-20.04'
        run: sudo apt install -quy libpcsclite-dev

      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Test Race
        run: go test -race -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::966137286427:role/github-actions-vitalvas-oneauth

      - name: Build and upload
        run: bash build.sh
      
      - name: Publish coverage
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./coverage.txt
          flags: ${{ matrix.os }}
