name: tests

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - uses: actions/checkout@v3
      
      - name: install deps
        run: sudo apt install -qy libpcsclite-dev

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
